name: "Projetos & Pesquisas"
description: "Lucas S. (Ls4ss)"
meta_description: "Ls4ss"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "lucassouza.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "lucassouza.io/lab"
author: "Lucas S."

# Disqus config
disqus-shortname: ""
