name: "Lucas Souza"
description: "Projetos & Pesquisas"
meta_description: "Ls4ss"

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: /
domain_name: "lucassouza.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "lucassouza.io/blog"
author: "Lucas S."

# Disqus config
disqus-shortname: ""
