name: Ls åss
description: Cybersecurity Research
meta_description: "Cybersecurity Research"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /blog
domain_name: "http://yourblog-domain.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Your Name"

# Disqus config
disqus-shortname: ""
