name: "Ls åss - Security Lab"
description: "by: Lucas S."
meta_description: "by: Lucas S."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "lsass.io/blog"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "lsass.io/blog"
author: "Lucas Souza"

# Disqus config
disqus-shortname: ""
