name: "Projetos & Pesquisas"
description: "Por: Lucas S."
meta_description: "by: Lucas S."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "me.log.br/blog/"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "me.log.br/blog/"
author: "Lucas S."

# Disqus config
disqus-shortname: ""
